"""Track provider

Revision ID: 1d32fb0740d7
Revises: a8a6d5d27dce
Create Date: 2022-03-21 08:02:15.132728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d32fb0740d7'
down_revision = 'a8a6d5d27dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'provider')
    # ### end Alembic commands ###
