"""Add origin

Revision ID: 32a76d57f568
Revises: 7615d5d8e354
Create Date: 2022-03-15 19:18:31.509379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a76d57f568'
down_revision = '7615d5d8e354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'origin')
    # ### end Alembic commands ###
