"""empty message

Revision ID: 33e16e437be7
Revises: d56d1895bf42
Create Date: 2021-03-02 15:16:10.979367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e16e437be7'
down_revision = 'd56d1895bf42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('pressure', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'temperature')
    op.drop_column('measurements', 'pressure')
    op.drop_column('measurements', 'humidity')
    # ### end Alembic commands ###
