"""Add provider

Revision ID: 5f79987ad376
Revises: fdc57cc1fccf
Create Date: 2022-03-16 08:15:28.354267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f79987ad376'
down_revision = 'fdc57cc1fccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'provider')
    # ### end Alembic commands ###
