"""Track providers

Revision ID: 691e64c5a637
Revises: a8a6d5d27dce
Create Date: 2022-03-23 18:38:13.797478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691e64c5a637'
down_revision = 'a8a6d5d27dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_measurement_provider', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_measurement_provider', type_='foreignkey')
        batch_op.drop_column('provider_id')
    # ### end Alembic commands ###
