"""Delete measurements on provider deletion

Revision ID: 817c1823e63c
Revises: 691e64c5a637
Create Date: 2023-03-16 14:24:51.290592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c1823e63c'
down_revision = '691e64c5a637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_measurement_provider', 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'providers', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key('fk_measurement_provider', 'measurements', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###
