"""empty message

Revision ID: 8a8d02c12409
Revises: 
Create Date: 2020-10-16 23:45:02.360525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8d02c12409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded', sa.DateTime(), nullable=True),
    sa.Column('sensor', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('pm1dot0', sa.Float(), nullable=True),
    sa.Column('pm2dot5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
