"""Rename to providers

Revision ID: a8a6d5d27dce
Revises: fdc57cc1fccf
Create Date: 2022-03-21 07:23:20.371657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a6d5d27dce'
down_revision = 'fdc57cc1fccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('api_keys', 'providers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('providers', 'api_keys')
    # ### end Alembic commands ###
