"""Rename source to origin

Revision ID: c9918163f182
Revises: 32a76d57f568
Create Date: 2022-03-15 19:30:24.802097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9918163f182'
down_revision = '32a76d57f568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys',
                     column_name = 'source',
                     new_column_name = 'origin',
                     existing_type = sa.VARCHAR(),
                     existing_nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys',
                     column_name = 'origin',
                     new_column_name = 'source',
                     existing_type = sa.VARCHAR(),
                     existing_nullable = False)
    # ### end Alembic commands ###
