"""CO2 Support

Revision ID: cd509524593e
Revises: 33e16e437be7
Create Date: 2021-12-31 10:02:44.366565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd509524593e'
down_revision = '33e16e437be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('co2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'co2')
    # ### end Alembic commands ###
