"""Add description field

Revision ID: d38d4e717fa5
Revises: 4331c2d45daf
Create Date: 2020-12-03 20:12:51.432062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38d4e717fa5'
down_revision = '4331c2d45daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'description')
    # ### end Alembic commands ###
