"""Rename source to provider

Revision ID: fdc57cc1fccf
Revises: 7615d5d8e354
Create Date: 2022-03-16 07:42:26.813065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc57cc1fccf'
down_revision = '7615d5d8e354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', column_name='source', new_column_name='provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', column_name='provider', new_column_name='source')
    # ### end Alembic commands ###
