# Basic Github Action to run a CI pipeline. It is triggered on
# push or pull requests events but only for the master branch.

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      - name: Setup Python 3.8 environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the QA script
        run: ./qa.sh
