# Basic Github Action to run a CI pipeline. It is triggered on
# push or pull requests events but only for the master branch.

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      - name: Setup Python 3.8 environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the QA script
        run: ./qa.sh
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"