# Basic REMOTE DEPLOY for LINKA

name: DEPLOY_TO_DEV

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Remotely instruct JENKINS to BUILD the PUSHED REPO in DEV ENVIRONMENT
      run: |
        curl -i -X POST "https://phoebe.roshka.com/jenkins/job/rald-dev-deploy/build" --user ${{ secrets.deploy_user }}:${{ secrets.deploy_token }}
        echo DONE

